-- AltArmy TBC — WoW Forever's Waylaid Crates and the bundles that fill them (Economy tab).
-- GENERATED by scripts/generate-waylaid-crates.py from the client's game data: do not edit by hand.
-- A shipment takes any ONE of its bundles. `kind`: Gathered (raw goods) or Crafted (crafted goods).
-- The unread "Waylaid Crate" (GENERIC) becomes a random shipment when its label is read.

if not AltArmy then return end

AltArmy.WaylaidCrates = AltArmy.WaylaidCrates or {}
local C = AltArmy.WaylaidCrates

C.GENERIC = 248549
C.TIERS = { "Apprentice", "Journeyman", "Expert", "Artisan" }
C.LIST = {
    { id = 248549, name = "Waylaid Crate", short = "Waylaid Crate (unread)", random = true, bundles = {} },
    { id = 248682, name = "Waylaid Crate: Apprentice Herbs", short = "Apprentice Herbs",
      tier = "Apprentice", kind = "Gathered", bundles = {
        { item = 2447, count = 20, name = "Peacebloom" },
        { item = 765, count = 20, name = "Silverleaf" },
        { item = 2449, count = 10, name = "Earthroot" },
        { item = 785, count = 10, name = "Mageroyal" },
        { item = 2450, count = 10, name = "Briarthorn" },
    } },
    { id = 248683, name = "Waylaid Crate: Apprentice Ore", short = "Apprentice Ore",
      tier = "Apprentice", kind = "Gathered", bundles = {
        { item = 2770, count = 20, name = "Copper Ore" },
        { item = 2771, count = 20, name = "Tin Ore" },
    } },
    { id = 248684, name = "Waylaid Crate: Apprentice Textiles", short = "Apprentice Textiles",
      tier = "Apprentice", kind = "Gathered", bundles = {
        { item = 2589, count = 40, name = "Linen Cloth" },
        { item = 2318, count = 20, name = "Light Leather" },
    } },
    { id = 248685, name = "Waylaid Crate: Apprentice Curiosities", short = "Apprentice Curiosities",
      tier = "Apprentice", kind = "Gathered", bundles = {
        { item = 10940, count = 20, name = "Strange Dust" },
        { item = 10939, count = 4, name = "Greater Magic Essence" },
        { item = 10978, count = 6, name = "Small Glimmering Shard" },
        { item = 11084, count = 2, name = "Large Glimmering Shard" },
    } },
    { id = 248686, name = "Waylaid Crate: Journeyman Herbs", short = "Journeyman Herbs",
      tier = "Journeyman", kind = "Gathered", bundles = {
        { item = 3820, count = 10, name = "Stranglekelp" },
        { item = 2453, count = 10, name = "Bruiseweed" },
        { item = 3355, count = 10, name = "Wild Steelbloom" },
        { item = 3369, count = 10, name = "Grave Moss" },
        { item = 3356, count = 10, name = "Kingsblood" },
    } },
    { id = 248687, name = "Waylaid Crate: Journeyman Ore", short = "Journeyman Ore",
      tier = "Journeyman", kind = "Gathered", bundles = {
        { item = 2775, count = 10, name = "Silver Ore" },
        { item = 2772, count = 20, name = "Iron Ore" },
    } },
    { id = 248688, name = "Waylaid Crate: Journeyman Textiles", short = "Journeyman Textiles",
      tier = "Journeyman", kind = "Gathered", bundles = {
        { item = 2592, count = 20, name = "Wool Cloth" },
        { item = 4306, count = 40, name = "Silk Cloth" },
        { item = 2319, count = 20, name = "Medium Leather" },
    } },
    { id = 248689, name = "Waylaid Crate: Journeyman Curiosities", short = "Journeyman Curiosities",
      tier = "Journeyman", kind = "Gathered", bundles = {
        { item = 11083, count = 20, name = "Soul Dust" },
        { item = 11082, count = 4, name = "Greater Astral Essence" },
        { item = 11138, count = 6, name = "Small Glowing Shard" },
        { item = 11139, count = 2, name = "Large Glowing Shard" },
    } },
    { id = 248690, name = "Waylaid Crate: Earthly Expert Herbs", short = "Earthly Expert Herbs",
      tier = "Expert", kind = "Gathered", bundles = {
        { item = 3357, count = 20, name = "Liferoot" },
        { item = 3818, count = 10, name = "Fadeleaf" },
        { item = 3821, count = 10, name = "Goldthorn" },
        { item = 3358, count = 10, name = "Khadgar's Whisker" },
    } },
    { id = 248691, name = "Waylaid Crate: Flowering Expert Herbs", short = "Flowering Expert Herbs",
      tier = "Expert", kind = "Gathered", bundles = {
        { item = 3819, count = 10, name = "Wintersbite" },
        { item = 4625, count = 10, name = "Firebloom" },
        { item = 8831, count = 20, name = "Purple Lotus" },
        { item = 8836, count = 10, name = "Arthas' Tears" },
    } },
    { id = 248692, name = "Waylaid Crate: Expert Ore", short = "Expert Ore",
      tier = "Expert", kind = "Gathered", bundles = {
        { item = 2776, count = 10, name = "Gold Ore" },
        { item = 3858, count = 20, name = "Mithril Ore" },
    } },
    { id = 248693, name = "Waylaid Crate: Expert Textiles", short = "Expert Textiles",
      tier = "Expert", kind = "Gathered", bundles = {
        { item = 4338, count = 40, name = "Mageweave Cloth" },
        { item = 4234, count = 20, name = "Heavy Leather" },
    } },
    { id = 248694, name = "Waylaid Crate: Expert Curiosities", short = "Expert Curiosities",
      tier = "Expert", kind = "Gathered", bundles = {
        { item = 11137, count = 20, name = "Vision Dust" },
        { item = 11135, count = 4, name = "Greater Mystic Essence" },
        { item = 11177, count = 6, name = "Small Radiant Shard" },
        { item = 11178, count = 2, name = "Large Radiant Shard" },
    } },
    { id = 248695, name = "Waylaid Crate: Earthly Artisan Herbs", short = "Earthly Artisan Herbs",
      tier = "Artisan", kind = "Gathered", bundles = {
        { item = 13464, count = 10, name = "Golden Sansam" },
        { item = 8838, count = 20, name = "Sungrass" },
        { item = 8839, count = 10, name = "Blindweed" },
        { item = 8845, count = 10, name = "Ghost Mushroom" },
        { item = 8846, count = 10, name = "Gromsblood" },
    } },
    { id = 248696, name = "Waylaid Crate: Flowering Artisan Herbs", short = "Flowering Artisan Herbs",
      tier = "Artisan", kind = "Gathered", bundles = {
        { item = 13463, count = 20, name = "Dreamfoil" },
        { item = 13465, count = 20, name = "Mountain Silversage" },
        { item = 13466, count = 20, name = "Plaguebloom" },
        { item = 13467, count = 20, name = "Icecap" },
    } },
    { id = 248697, name = "Waylaid Crate: Artisan Ore", short = "Artisan Ore",
      tier = "Artisan", kind = "Gathered", bundles = {
        { item = 7911, count = 10, name = "Truesilver Ore" },
        { item = 10620, count = 20, name = "Thorium Ore" },
        { item = 11370, count = 20, name = "Dark Iron Ore" },
    } },
    { id = 248698, name = "Waylaid Crate: Artisan Textiles", short = "Artisan Textiles",
      tier = "Artisan", kind = "Gathered", bundles = {
        { item = 14047, count = 40, name = "Runecloth" },
        { item = 4304, count = 20, name = "Thick Leather" },
        { item = 8170, count = 20, name = "Rugged Leather" },
    } },
    { id = 248699, name = "Waylaid Crate: Artisan Curiosities", short = "Artisan Curiosities",
      tier = "Artisan", kind = "Gathered", bundles = {
        { item = 11176, count = 20, name = "Dream Dust" },
        { item = 11175, count = 4, name = "Greater Nether Essence" },
        { item = 14343, count = 6, name = "Small Brilliant Shard" },
        { item = 14344, count = 2, name = "Large Brilliant Shard" },
    } },
    { id = 248702, name = "Waylaid Crate: Apprentice Fabrics", short = "Apprentice Fabrics",
      tier = "Apprentice", kind = "Crafted", bundles = {
        { item = 4231, count = 2, name = "Cured Light Hide" },
        { item = 2996, count = 20, name = "Bolt of Linen Cloth" },
    } },
    { id = 248703, name = "Waylaid Crate: Apprentice Ingots", short = "Apprentice Ingots",
      tier = "Apprentice", kind = "Crafted", bundles = {
        { item = 2840, count = 20, name = "Copper Bar" },
        { item = 3576, count = 20, name = "Tin Bar" },
        { item = 2841, count = 10, name = "Bronze Bar" },
    } },
    { id = 248704, name = "Waylaid Crate: Apprentice Parts", short = "Apprentice Parts",
      tier = "Apprentice", kind = "Crafted", bundles = {
        { item = 4359, count = 16, name = "Handful of Copper Bolts" },
        { item = 4361, count = 16, name = "Copper Tube" },
        { item = 4363, count = 4, name = "Copper Modulator" },
    } },
    { id = 248705, name = "Waylaid Crate: Journeyman Fabrics", short = "Journeyman Fabrics",
      tier = "Journeyman", kind = "Crafted", bundles = {
        { item = 2997, count = 6, name = "Bolt of Woolen Cloth" },
        { item = 4305, count = 10, name = "Bolt of Silk Cloth" },
        { item = 4233, count = 2, name = "Cured Medium Hide" },
    } },
    { id = 248706, name = "Waylaid Crate: Journeyman Ingots", short = "Journeyman Ingots",
      tier = "Journeyman", kind = "Crafted", bundles = {
        { item = 2842, count = 10, name = "Silver Bar" },
        { item = 3575, count = 20, name = "Iron Bar" },
    } },
    { id = 248707, name = "Waylaid Crate: Journeyman Parts", short = "Journeyman Parts",
      tier = "Journeyman", kind = "Crafted", bundles = {
        { item = 4371, count = 8, name = "Bronze Tube" },
        { item = 4375, count = 7, name = "Whirring Bronze Gizmo" },
        { item = 4382, count = 4, name = "Bronze Framework" },
        { item = 10558, count = 45, name = "Gold Power Core" },
    } },
    { id = 248708, name = "Waylaid Crate: Expert Fabrics", short = "Expert Fabrics",
      tier = "Expert", kind = "Crafted", bundles = {
        { item = 4339, count = 8, name = "Bolt of Mageweave" },
        { item = 4236, count = 2, name = "Cured Heavy Hide" },
    } },
    { id = 248709, name = "Waylaid Crate: Expert Ingots", short = "Expert Ingots",
      tier = "Expert", kind = "Crafted", bundles = {
        { item = 3860, count = 20, name = "Mithril Bar" },
        { item = 3859, count = 15, name = "Steel Bar" },
        { item = 3577, count = 10, name = "Gold Bar" },
    } },
    { id = 248710, name = "Waylaid Crate: Expert Parts", short = "Expert Parts",
      tier = "Expert", kind = "Crafted", bundles = {
        { item = 4387, count = 8, name = "Iron Strut" },
        { item = 10559, count = 5, name = "Mithril Tube" },
        { item = 10560, count = 12, name = "Unstable Trigger" },
        { item = 10561, count = 5, name = "Mithril Casing" },
    } },
    { id = 248711, name = "Waylaid Crate: Artisan Fabrics", short = "Artisan Fabrics",
      tier = "Artisan", kind = "Crafted", bundles = {
        { item = 14048, count = 8, name = "Bolt of Runecloth" },
        { item = 8172, count = 2, name = "Cured Thick Hide" },
    } },
    { id = 248712, name = "Waylaid Crate: Artisan Ingots", short = "Artisan Ingots",
      tier = "Artisan", kind = "Crafted", bundles = {
        { item = 11371, count = 2, name = "Dark Iron Bar" },
        { item = 6037, count = 10, name = "Truesilver Bar" },
        { item = 12359, count = 20, name = "Thorium Bar" },
    } },
    { id = 248713, name = "Waylaid Crate: Artisan Parts", short = "Artisan Parts",
      tier = "Artisan", kind = "Crafted", bundles = {
        { item = 15994, count = 5, name = "Thorium Widget" },
        { item = 18631, count = 5, name = "Truesilver Transformer" },
        { item = 16000, count = 2, name = "Thorium Tube" },
    } },
}

C.ById = {}
for _, crate in ipairs(C.LIST) do
    C.ById[crate.id] = crate
end
