-- AltArmy TBC — recipe metadata from the bundled per-client table (Data/Recipes/RecipeData_*.lua):
-- profession, crafted item, required skill, difficulty bands and where a recipe is learned.
-- The tables are generated by scripts/generate-recipe-data.py (see Data/DESIGN.md, "Recipe data").

AltArmy = AltArmy or {}
AltArmy.RecipeInfo = AltArmy.RecipeInfo or {}

local RI = AltArmy.RecipeInfo

-- Positional fields of a RecipeData row; false marks an unknown value.
local F = { profession = 1, resultItemID = 2, reqSkill = 3, yellow = 4, gray = 5, source = 6, recipeItemID = 7 }

local MAX_SKILL = 375

-- Profession key -> spell whose (localized) name is the profession's name in the client.
RI.PROFESSION_SPELL_IDS = {
    alchemy = 2259,
    blacksmithing = 2018,
    cooking = 2550,
    enchanting = 7411,
    engineering = 4036,
    firstAid = 3273,
    jewelcrafting = 25229,
    leatherworking = 2108,
    mining = 2575,
    poisons = 2842,
    tailoring = 3908,
}

-- Fallback when GetSpellInfo can't name a profession (tests, unusual clients).
local ENGLISH_PROFESSION_NAMES = {
    alchemy = "Alchemy",
    blacksmithing = "Blacksmithing",
    cooking = "Cooking",
    enchanting = "Enchanting",
    engineering = "Engineering",
    firstAid = "First Aid",
    jewelcrafting = "Jewelcrafting",
    leatherworking = "Leatherworking",
    mining = "Mining",
    poisons = "Poisons",
    tailoring = "Tailoring",
}

-- AARRGGBB (WoW |cAARRGGBB format)
local DIFFICULTY_HEX = {
    orange = "ffff8040",
    yellow = "ffffff00",
    green = "ff40ff40",
    gray = "ff808080",
}

local DIFFICULTY_HARDNESS = { orange = 1, yellow = 2, green = 3, gray = 4 }

local cache = {
    recipes = {}, -- spellID -> record or false
    byResultItem = nil, -- itemID -> { spellID, ... } (lazy)
    byName = nil, -- client recipe name -> { spellID, ... } (lazy)
    enrich = {}, -- "profession:recipeID:resultItemID" -> record or false
    professionKeys = {}, -- profession display name -> key or false
}

local function clearTable(t)
    for k in pairs(t) do
        t[k] = nil
    end
end

-- Self-contained spell-name lookup (no DataStore load-order dependency): legacy GetSpellInfo is absent
-- on some clients (WoW Forever beta; see docs/WOW_FOREVER_COMPATIBILITY_RESEARCH.md).
local function spellName(spellID)
    local name
    if GetSpellInfo then
        name = GetSpellInfo(spellID)
    elseif C_Spell and C_Spell.GetSpellInfo then
        local info = C_Spell.GetSpellInfo(spellID)
        name = info and info.name
    end
    if type(name) == "string" and name ~= "" then
        return name
    end
    return nil
end

local function recipeRows()
    local data = AltArmy.RecipeData
    return data and data.recipes
end

local function known(v)
    if v == false then
        return nil
    end
    return v
end

function RI.IsAvailable()
    return recipeRows() ~= nil
end

--- Recipe record for a recipe spell id, or nil:
--- { recipeID, professionKey, resultItemID, reqSkill, yellow, gray, source, recipeItemID } (unknown = nil;
--- an enchant has no resultItemID).
function RI.GetRecipe(spellID)
    spellID = tonumber(spellID)
    if not spellID then
        return nil
    end
    local cached = cache.recipes[spellID]
    if cached ~= nil then
        return cached or nil
    end
    local rows = recipeRows()
    local row = rows and rows[spellID]
    if not row then
        cache.recipes[spellID] = false
        return nil
    end
    local result = known(row[F.resultItemID])
    local record = {
        recipeID = spellID,
        professionKey = row[F.profession],
        resultItemID = (result and result > 0) and result or nil,
        reqSkill = known(row[F.reqSkill]),
        yellow = known(row[F.yellow]),
        gray = known(row[F.gray]),
        source = known(row[F.source]),
        recipeItemID = known(row[F.recipeItemID]),
    }
    cache.recipes[spellID] = record
    return record
end

--- Localized profession name for a profession key.
function RI.GetProfessionName(professionKey)
    local spellID = RI.PROFESSION_SPELL_IDS[professionKey]
    return (spellID and spellName(spellID)) or ENGLISH_PROFESSION_NAMES[professionKey]
end

--- Profession key for a (localized) profession display name, or nil.
function RI.ResolveProfessionKey(professionName)
    if type(professionName) ~= "string" or professionName == "" then
        return nil
    end
    local cached = cache.professionKeys[professionName]
    if cached ~= nil then
        return cached or nil
    end
    local found = false
    for key in pairs(RI.PROFESSION_SPELL_IDS) do
        if RI.GetProfessionName(key) == professionName or ENGLISH_PROFESSION_NAMES[key] == professionName then
            found = key
            break
        end
    end
    cache.professionKeys[professionName] = found
    return found or nil
end

local function sortedIndex(keyOf)
    local index = {}
    local spells = {}
    for spellID in pairs(recipeRows() or {}) do
        spells[#spells + 1] = spellID
    end
    table.sort(spells)
    for _, spellID in ipairs(spells) do
        local key = keyOf(spellID)
        if key ~= nil then
            local list = index[key]
            if not list then
                list = {}
                index[key] = list
            end
            list[#list + 1] = spellID
        end
    end
    return index
end

local function spellsByResultItem(itemID)
    if not cache.byResultItem then
        cache.byResultItem = sortedIndex(function(spellID)
            local record = RI.GetRecipe(spellID)
            return record and record.resultItemID
        end)
    end
    return cache.byResultItem[itemID]
end

local function spellsByName(name)
    if not cache.byName then
        cache.byName = sortedIndex(spellName)
    end
    return cache.byName[name]
end

--- First candidate recipe accepted by `accepts` (nil accepts any).
local function pickRecipe(spellIDs, accepts)
    for _, spellID in ipairs(spellIDs or {}) do
        local record = RI.GetRecipe(spellID)
        if record and (not accepts or accepts(record)) then
            return record
        end
    end
    return nil
end

--- Recipe for a stored recipe row: its spell id when that belongs to the row's profession, else the
--- profession's recipe crafting the row's result item.
local function lookupForEntry(professionName, recipeID, resultItemID)
    local professionKey = RI.ResolveProfessionKey(professionName)
    local function fits(record)
        return not professionKey or record.professionKey == professionKey
    end
    local record = RI.GetRecipe(recipeID)
    if record and fits(record) then
        return record
    end
    resultItemID = tonumber(resultItemID)
    if resultItemID then
        return pickRecipe(spellsByResultItem(resultItemID), fits)
    end
    return nil
end

function RI.IsValidSkillRequired(value)
    local n = tonumber(value)
    return n ~= nil and n >= 1 and n <= MAX_SKILL
end

--- "orange" / "yellow" / "green" / "gray" at a skill rank, or nil without difficulty bands.
--- Green starts at the floored midpoint of yellow and gray.
function RI.GetDifficulty(record, playerSkill)
    if not record or not record.yellow or not record.gray then
        return nil
    end
    local skill = tonumber(playerSkill) or 0
    local green = math.floor((record.yellow + record.gray) / 2)
    if skill < record.yellow then
        return "orange"
    elseif skill < green then
        return "yellow"
    elseif skill < record.gray then
        return "green"
    end
    return "gray"
end

function RI.GetDifficultyColorHex(difficulty)
    if not difficulty then
        return nil
    end
    return DIFFICULTY_HEX[difficulty]
end

--- True when any of a recipe's "|"-joined sources is enabled in a source filter map.
function RI.SourceIncludes(source, filter)
    if type(source) ~= "string" or type(filter) ~= "table" then
        return false
    end
    for kind in source:gmatch("[^|]+") do
        if filter[kind] then
            return true
        end
    end
    return false
end

--- Enrich a search/guild recipe entry (mutates entry): recipeSkillRequired, difficulty (at
--- entry.skillRank), recipeSource, and resultItemID when missing. The recipe lookup is cached per
--- profession + ids; difficulty is recomputed for each entry's skill rank.
function RI.EnrichEntry(entry)
    if not entry or not RI.IsAvailable() then
        return entry
    end
    local cacheKey = tostring(entry.professionName or "") .. ":"
        .. tostring(entry.recipeID or "") .. ":" .. tostring(entry.resultItemID or "")
    local record = cache.enrich[cacheKey]
    if record == nil then
        record = lookupForEntry(entry.professionName, entry.recipeID, entry.resultItemID) or false
        cache.enrich[cacheKey] = record
    end
    if not record then
        entry.recipeSkillRequired = nil
        entry.difficulty = nil
        entry.recipeSource = nil
        return entry
    end
    entry.recipeSkillRequired = RI.IsValidSkillRequired(record.reqSkill) and record.reqSkill or nil
    entry.difficulty = RI.GetDifficulty(record, entry.skillRank or 0)
    entry.recipeSource = record.source
    if not entry.resultItemID and record.resultItemID then
        entry.resultItemID = record.resultItemID
    end
    return entry
end

local function learnInfo(record)
    if not record then
        return nil
    end
    return {
        professionName = RI.GetProfessionName(record.professionKey),
        professionKey = record.professionKey,
        recipeID = record.recipeID,
        resultItemID = record.resultItemID,
    }
end

--- Which recipe a learn signal means: a recipe spell id (NEW_RECIPE_LEARNED), a crafted item id, or the
--- recipe name from the learn chat line (client language). `knownProfessions` (optional, profession
--- display name -> truthy) breaks ties when professions share a recipe name.
--- Returns { professionName, professionKey, recipeID, resultItemID } or nil.
function RI.FindRecipeLearnInfo(spellID, recipeName, knownProfessions)
    if not RI.IsAvailable() then
        return nil
    end
    local function preferKnown(spellIDs)
        if type(knownProfessions) == "table" then
            local record = pickRecipe(spellIDs, function(r)
                return knownProfessions[RI.GetProfessionName(r.professionKey)] and true or false
            end)
            if record then
                return record
            end
        end
        return pickRecipe(spellIDs)
    end
    local id = tonumber(spellID)
    if id then
        local record = RI.GetRecipe(id) or preferKnown(spellsByResultItem(id))
        if record then
            return learnInfo(record)
        end
    end
    if type(recipeName) == "string" and recipeName ~= "" then
        return learnInfo(preferKnown(spellsByName(recipeName)))
    end
    return nil
end

--- Colored skill cell text: recipeRequired/playerSkill, or player skill only when unknown.
function RI.FormatSkillCell(recipeRequired, playerSkill, difficulty)
    local req = tonumber(recipeRequired)
    local rank = tonumber(playerSkill) or 0
    if not RI.IsValidSkillRequired(req) then
        if rank > 0 then
            return tostring(rank)
        end
        return "—"
    end
    local hex = RI.GetDifficultyColorHex(difficulty) or "ffffffff"
    return string.format("|c%s%d|r/%d", hex, req, rank)
end

--- Hardest difficulty among a list (`orange` > `yellow` > `green` > `gray`).
--- Ignores nil/unknown values; returns nil when none are valid.
function RI.PickHardestDifficulty(difficulties)
    if type(difficulties) ~= "table" then
        return nil
    end
    local best
    local bestOrd
    for i = 1, #difficulties do
        local d = difficulties[i]
        local ord = d and DIFFICULTY_HARDNESS[d]
        if ord and (not bestOrd or ord < bestOrd) then
            best = d
            bestOrd = ord
        end
    end
    return best
end

--- Collapsed multi-guildmate skill cell: colored recipeRequired/***, or "*" when unknown.
function RI.FormatCollapsedSkillCell(recipeRequired, difficulty)
    local req = tonumber(recipeRequired)
    if not RI.IsValidSkillRequired(req) then
        return "*"
    end
    local hex = RI.GetDifficultyColorHex(difficulty) or "ffffffff"
    return string.format("|c%s%d|r/***", hex, req)
end

function RI.ClearCaches()
    clearTable(cache.recipes)
    clearTable(cache.enrich)
    clearTable(cache.professionKeys)
    cache.byResultItem = nil
    cache.byName = nil
end
