"""Regenerate AltArmy_TBC/Data/Economy/WaylaidCrates.lua: WoW Forever's Waylaid Crates and their bundles.

Usage: python scripts/generate-waylaid-crates.py [--db <altarmy-profit sqlite>] [--out <lua file>] [--check]

Reads the game data altarmy-profit imports from the client's DB2 tables (the `items` table,
game_version 'forever'). Each shipment crate's Use text lists the bundles that fill it, any one of
them ("Fill the crate with any bundle from the following list: - 20 Peacebloom - 20 Silverleaf ...");
bundle names are resolved to item ids here so the addon needs no item lookups. Stdlib only.
Rerun after a Forever patch changes the crates (re-ingest altarmy-profit first). altarmy-profit's
`ingest` runs this itself when it loads Forever data into its SQLite file and this repo sits next to it.

--check writes nothing: it exits 1 when --out differs from what the game data gives (the pre-commit hook,
.githooks/pre-commit), and 0 with a note when the database isn't there to check against.
"""
import argparse
import json
import os
import re
import sqlite3
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
DEFAULT_DB = os.path.join(ROOT, "..", "wow-profit", "data", "altarmy-profit.sqlite")
DEFAULT_OUT = os.path.join(ROOT, "AltArmy_TBC", "Data", "Economy", "WaylaidCrates.lua")

GENERIC = 248549  # "Waylaid Crate": read its label to learn which shipment it is
FIRST, LAST = 248682, 248713  # the shipments ("Waylaid Crate: Apprentice Herbs", ...)
TIERS = ("Apprentice", "Journeyman", "Expert", "Artisan")
KIND_BY_QUALITY = {1: "Gathered", 2: "Crafted"}  # white crates take raw goods, green crates crafted ones
# Names that match more than one unbound item. Dark Iron Ore 11099 is a stack-of-10 quest variant.
OVERRIDES = {"Dark Iron Ore": 11370}
BUNDLE_LINE = re.compile(r"^- (\d+) (.+?)(?:\|r)?\s*$")


def use_text(effects_json):
    for effect in json.loads(effects_json or "[]"):
        if effect.get("trigger") == "Use":
            return effect.get("text") or ""
    return ""


def resolve(db, name):
    if name in OVERRIDES:
        return OVERRIDES[name]
    rows = db.execute(
        "SELECT id FROM items WHERE game_version='forever' AND name=? AND bonding=0", (name,)
    ).fetchall()
    if len(rows) != 1:
        sys.exit(f"bundle item {name!r} matches {len(rows)} tradeable items; add it to OVERRIDES")
    return rows[0][0]


def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def build(db_path):
    """The Lua module's text, from the altarmy-profit database at `db_path`."""
    db = sqlite3.connect(f"file:{os.path.abspath(db_path)}?mode=ro", uri=True)
    rows = db.execute(
        "SELECT id, name, quality, effects FROM items WHERE game_version='forever'"
        " AND (id BETWEEN ? AND ? OR id=?) AND name LIKE 'Waylaid Crate%' ORDER BY id",
        (FIRST, LAST, GENERIC),
    ).fetchall()
    if len(rows) != 31:
        sys.exit(f"expected 31 Waylaid Crates, found {len(rows)}")

    out = [
        "-- AltArmy TBC — WoW Forever's Waylaid Crates and the bundles that fill them (Economy tab).",
        "-- GENERATED by scripts/generate-waylaid-crates.py from the client's game data: do not edit by hand.",
        "-- A shipment takes any ONE of its bundles. `kind`: Gathered (raw goods) or Crafted (crafted goods).",
        "-- The unread \"Waylaid Crate\" (GENERIC) becomes a random shipment when its label is read.",
        "",
        "if not AltArmy then return end",
        "",
        "AltArmy.WaylaidCrates = AltArmy.WaylaidCrates or {}",
        "local C = AltArmy.WaylaidCrates",
        "",
        f"C.GENERIC = {GENERIC}",
        "C.TIERS = { " + ", ".join(lua_str(t) for t in TIERS) + " }",
        "C.LIST = {",
    ]
    for item_id, name, quality, effects in rows:
        if item_id == GENERIC:
            out.append(
                f"    {{ id = {item_id}, name = {lua_str(name)}, short = {lua_str(name + ' (unread)')},"
                " random = true, bundles = {} },"
            )
            continue
        tier = next((t for t in TIERS if t in name), None)
        kind = KIND_BY_QUALITY.get(quality)
        if not tier or not kind:
            sys.exit(f"{item_id} {name!r}: no tier or kind")
        bundles = []
        for line in use_text(effects).replace("|cnIQ1:", "\n").splitlines():
            m = BUNDLE_LINE.match(line.strip())
            if m:
                count, bname = int(m.group(1)), m.group(2).strip()
                bundles.append((resolve(db, bname), count, bname))
        if len(bundles) < 2:
            sys.exit(f"{item_id} {name!r}: found {len(bundles)} bundles")
        short = name.split(": ", 1)[1]
        out.append(
            f"    {{ id = {item_id}, name = {lua_str(name)}, short = {lua_str(short)},"
        )
        out.append(f"      tier = {lua_str(tier)}, kind = {lua_str(kind)}, bundles = {{")
        for bid, count, bname in bundles:
            out.append(f"        {{ item = {bid}, count = {count}, name = {lua_str(bname)} }},")
        out.append("    } },")
    out += [
        "}",
        "",
        "C.ById = {}",
        "for _, crate in ipairs(C.LIST) do",
        "    C.ById[crate.id] = crate",
        "end",
        "",
    ]
    db.close()
    return "\n".join(out), len(rows)


def read_normalized(path):
    """The file's text with LF line endings (git may check it out with CRLF), or None if it's missing."""
    try:
        with open(path, encoding="utf-8") as f:
            return f.read().replace("\r\n", "\n")
    except FileNotFoundError:
        return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default=DEFAULT_DB)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--check", action="store_true", help="exit 1 if --out is out of date; write nothing")
    args = ap.parse_args()
    if args.check and not os.path.isfile(args.db):
        print(f"Waylaid Crates check skipped: no altarmy-profit database at {os.path.abspath(args.db)}")
        return
    text, count = build(args.db)
    if args.check:
        if read_normalized(args.out) != text:
            sys.exit(
                f"{os.path.relpath(args.out)} is out of date with altarmy-profit's game data.\n"
                "Run `python scripts/generate-waylaid-crates.py` and commit the change."
            )
        return
    if read_normalized(args.out) == text:
        print(f"{args.out}: already up to date ({count} crates)")
        return
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {args.out}: {count} crates")


if __name__ == "__main__":
    main()
